### ISSUE TITLE
npm installs NoFlo 0.4.5 instead of the 0.5.x version in package.json

### ISSUE THREAD

**Issue by brechtcs** [noflo/noflo-jekyll#10]
After installing this module through npm I got "object has no method..." errors similar to [this one](http://stackoverflow.com/questions/24295978/noflo-error-typeerror-object-port-arrayport-has-no-method-isaddressable): 

Assuming that the causes were similar, I checked which NoFlo version was installed as a dependency, and as expected it did turn out to be a pre-0.5 version. However the package.json file correctly lists 0.5.x. Any idea why my npm reverts back to the 0.4.5 version anyway?

**Comment by brechtcs** [comment]
For reference, here's the full console log I get when trying to run it with my outdated NoFlo version:

> /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/src/components/Graph.coffee:125
>       if (!port.canAttach()) {
>                 ^
> TypeError: Object #<Object> has no method 'canAttach'
>   at Graph.isExported (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/src/components/Graph.coffee:7:3)
>   at Graph.findEdgePorts (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/src/components/Graph.coffee:95:9)
>   at Graph.checkComponent (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/src/components/Graph.coffee:66:5)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/src/components/Graph.coffee:59:7
>   at networkReady (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/NoFlo.js:38:9)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/NoFlo.js:56:16
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at Network.addInitial (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:409:16)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at Network.addInitial (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:409:16)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:209:16
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at Network.addEdge (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:359:16)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at Network.addEdge (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:359:16)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at Network.addEdge (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:359:16)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at Network.addEdge (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:359:16)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at Network.addEdge (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:359:16)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at Network.addEdge (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:359:16)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at Network.addEdge (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:359:16)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:212:16
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:156:18
>   at ComponentLoader.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/ComponentLoader.js:134:14)
>   at Network.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:113:26)
>   at Network.addNode (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:135:19)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:156:18
>   at ComponentLoader.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/ComponentLoader.js:134:14)
>   at Network.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:113:26)
>   at Network.addNode (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:135:19)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:156:18
>   at ComponentLoader.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/ComponentLoader.js:134:14)
>   at Network.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:113:26)
>   at Network.addNode (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:135:19)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:156:18
>   at ComponentLoader.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/ComponentLoader.js:134:14)
>   at Network.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:113:26)
>   at Network.addNode (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:135:19)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:156:18
>   at ComponentLoader.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/ComponentLoader.js:134:14)
>   at Network.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:113:26)
>   at Network.addNode (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:135:19)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:156:18
>   at ComponentLoader.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/ComponentLoader.js:134:14)
>   at Network.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:113:26)
>   at Network.addNode (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:135:19)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:203:20
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:156:18
>   at ComponentLoader.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/ComponentLoader.js:134:14)
>   at Network.load (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:113:26)
>   at Network.addNode (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:135:19)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:202:37
>   at Network.connect (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Network.js:214:14)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/NoFlo.js:55:22
>   at ComponentLoader.listComponents (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/nodejs/ComponentLoader.js:132:16)
>   at Object.exports.createNetwork (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/NoFlo.js:48:20)
>   at Graph.createNetwork (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/src/components/Graph.coffee:54:36)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/src/components/Graph.coffee:32:5
>   at Object.exports.loadJSON (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Graph.js:536:12)
>   at Object.exports.loadFBP (/usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Graph.js:542:20)
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/Graph.js:562:24
>   at fs.js:271:14
>   at /usr/local/lib/node_modules/noflo-jekyll/node_modules/noflo/node_modules/read-installed/node_modules/graceful-fs/graceful-fs.js:90:5
>   at Object.oncomplete (fs.js:107:15)

**Comment by ebaioni** [comment]
Hi there,
I'm experiencing the exact same issue, is there any update on this?

Cheers
