### ISSUE TITLE
Did the concept editor in the readme ever get implemented?

### ISSUE THREAD

**Issue by Qix-** [noflo/noflo-jekyll#14]
Hey, kind of unrelated question but did [this editor](http://cdn.thegrid.io.s3.amazonaws.com/noflo/kickstarter/images/cards-v4-kickstarter-up.jpg) ever actually get made? Or is it just a concept art piece for the Kickstarter? It looks entirely different than the noflo editor that exists today, and I can't find any information as to why there is a discrepancy.

I would love to play with it - it's absolutely gorgeous. Figured this was the best place to ask since the Jekyll example is the only place I can find it.

**Comment by bergie** [comment]
Hey, it did get implemented. That is a real screenshot of https://github.com/meemoo/dataflow

However, we wanted to make this more mobile-friendly, and hence switched to a different design with https://github.com/flowhub/the-graph

**Comment by Qix-** [comment]
Thanks! Appreciate it :)
