### ISSUE TITLE
Error on run: Object #<ParseMarkdown> has no method 'getIcon'

### ISSUE THREAD

**Issue by bfulop** [noflo/noflo-jekyll#5]
I wanted to try out noflo-jekyll.
When I run `noflo-jekyll source _site`, I get the following error:

```
/Users/balint/.nvm/v0.10.13/lib/node_modules/noflo-jekyll/node_modules/noflo/lib/ComponentLoader.js:165
      if (instance.getIcon()) {
                   ^
TypeError: Object #<ParseMarkdown> has no method 'getIcon'
```

I have installed noflo and noflo-jekyll globally today.

**Comment by bergie** [comment]
The issue is that noflo-markdown is depending on too old NoFlo version. I'll release a fix soon

**Comment by bergie** [comment]
@bfulop done, try with https://npmjs.org/package/noflo-markdown
